name: notification_centre
description: A lightweight publisher/observer open-source library used for messaging to run through the entire Flutter applications.
version: 0.0.2
repository: https://github.com/VictorZhang2014/NotificationCentre
issue_tracker: https://github.com/VictorZhang2014/NotificationCentre/issues

environment:
  sdk: ">=2.19.0 <4.0.0" 
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.0
  test: ^1.24.0
