name: notification_centre
description: A lightweight publisher/observer open-source library used for messaging run through the entire Flutter application. 
version: 0.0.1
repository: https://github.com/VictorZhang2014/notification_centre

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
